#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2154
source /scripts/common

"${s6wrap[@]}" echo "[INFO] Starting Skies-ADSB version $(cat /.CONTAINER_VERSION)"

# configure SBS source
if [[ -z "$SBS_SOURCE" ]]; then
	"${s6wrap[@]}" echo "[ERROR] SBS_SOURCE environment variable is not set. Cannot continue - container halted!"
	exec sleep infinity
else
	mkdir -p /skies-adsb/src
	if [[ -f /skies-adsb/maps/data/.env ]]; then cp -f /skies-adsb/maps/data/.env /skies-adsb/src/.env; fi
	if [[ -f /skies-adsb/src/.env ]] && grep -qe '^VITE_USE_EXISTING_ADSB=.*$' /skies-adsb/src/.env ; then
	  sed -i 's|^\(VITE_USE_EXISTING_ADSB=\).*$|\1'"$SBS_SOURCE"'|g' /skies-adsb/src/.env
  else
		echo "VITE_USE_EXISTING_ADSB=$SBS_SOURCE" >> /skies-adsb/src/.env
	fi
	cp -f /skies-adsb/src/.env /skies-adsb/maps/data/.env
fi

# Enable web access for all:
cat <<EOF >/skies-adsb/vite.config.js
import { defineConfig } from "vite";

export default defineConfig({   
    root: 'src',
    build: {
        outDir: '../dist',
    },
    publicDir: '../public',
    server: {
      allowedHosts: true,
    }
})
EOF